# Tasks to install and maintain a Calibre instance.

- name: Install Calibre package.
  apt:
    name: calibre
    state: latest

- name: Create Calibre system user.
  user:
    name: "{{ calibre_server_username }}"
    state: present
    system: yes
    home: "{{ calibre_server_home_dir }}"
    groups: "{{ calibre_server_user_groups }}"
    shell: "/bin/sh"
    generate_ssh_key: yes
    ssh_key_type: ed25519
    ssh_key_comment: "Librarian"
    ssh_key_file: ".ssh/{{ calibre_server_username }}_librarian_ed25519"
    #ssh_key_passphrase: "{{ calibre_user_ssh_key_passphrase }}"

- name: Fetch the Calibre user's SSH keys for future management use.
  fetch:
    dest: "~/.ssh/"
    src: "{{ item }}"
  loop:
    - "{{ calibre_server_home_dir }}/.ssh/{{ calibre_server_username }}_librarian_ed25519"
    - "{{ calibre_server_home_dir }}/.ssh/{{ calibre_server_username }}_librarian_ed25519.pub"

- name: Set local filesystem permissions on fetched SSH keys.
  become: no
  local_action:
    module: file
    path: "~/.ssh/{{ inventory_hostname }}/{{ calibre_server_home_dir }}/.ssh/{{ item.file }}"
    mode: "{{ item.mode }}"
    owner: "{{ lookup('env', 'USER') }}"
  loop: "{{ files }}"
  vars:
    files:
      - {
        file: "{{ calibre_server_username }}_librarian_ed25519",
        mode: "600"
      }
      - {
        file: "{{ calibre_server_username }}_librarian_ed25519.pub",
        mode: "644"
      }

- name: Authorize Calibre user's newly generated SSH key.
  authorized_key:
    key: "{{ lookup('file', lookup('vars', 'public_key_file')) }}"
    state: present
    user: "{{ calibre_server_username }}"
  vars:
    public_key_file: "~/.ssh/{{ inventory_hostname }}/{{ calibre_server_home_dir }}/.ssh/{{ calibre_server_username }}_librarian_ed25519.pub"

- name: Install logrotate configuration for Calibre.
  template:
    src: calibre-server.logrotate.conf
    dest: /etc/logrotate.d/calibre-server
    # TODO: Can we validate? `logrotate(8)` has the `-d` switch, but…?

- name: Install Calibre systemd service unit file.
  template:
    src: calibre.service
    dest: /etc/systemd/system/calibre.service
    # TODO: Can we get validation to work?
    #validate: "systemd-analyze verify %s"
  # TODO: Despite being a loop, this only works with one Library.
  loop: "{{ calibre_libraries }}"

- name: Start Calibre content server via systemd.
  systemd:
    daemon_reload: yes
    name: calibre
    enabled: yes
    state: started
