---
# Handlers for Calibre role.

- name: Reload systemd daemon.
  systemd:
    daemon_reload: yes

- name: Restart Calibre.
  service:
    name: "calibre@{{ item.name }}.service"
    state: restarted
  loop: "{{ calibre_libraries }}"
